
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'DiceRoll': typeof import("../../app/components/DiceRoll.vue").default
  'DndHr': typeof import("../../app/components/DndHr.vue").default
  'EditionSelector': typeof import("../../app/components/EditionSelector.vue").default
  'BadgesBadgeBase': typeof import("../../app/components/badges/BadgeBase.vue").default
  'BadgesBadgeContainer': typeof import("../../app/components/badges/BadgeContainer.vue").default
  'BadgesCategoryBadge': typeof import("../../app/components/badges/CategoryBadge.vue").default
  'BadgesGameEditionBadge': typeof import("../../app/components/badges/GameEditionBadge.vue").default
  'BadgesPublicationTypeBadge': typeof import("../../app/components/badges/PublicationTypeBadge.vue").default
  'ButtonsBackButton': typeof import("../../app/components/buttons/BackButton.vue").default
  'ButtonsBaseButton': typeof import("../../app/components/buttons/BaseButton.vue").default
  'ButtonsEditionSelectorButton': typeof import("../../app/components/buttons/EditionSelectorButton.vue").default
  'ButtonsProductLinkButton': typeof import("../../app/components/buttons/ProductLinkButton.vue").default
  'CampaignSettingsCampaignSettingCard': typeof import("../../app/components/campaign-settings/CampaignSettingCard.vue").default
  'CampaignSettingsCampaignSettingListItem': typeof import("../../app/components/campaign-settings/CampaignSettingListItem.vue").default
  'CampaignSettingsCampaignSettingTeaser': typeof import("../../app/components/campaign-settings/CampaignSettingTeaser.vue").default
  'CardsBaseCard': typeof import("../../app/components/cards/BaseCard.vue").default
  'CardsTabsCard': typeof import("../../app/components/cards/TabsCard.vue").default
  'CharacterClassesCharacterClassTeaser': typeof import("../../app/components/characterClasses/CharacterClassTeaser.vue").default
  'CharacterClassesPrestigeClassTeaser': typeof import("../../app/components/characterClasses/PrestigeClassTeaser.vue").default
  'ContainersDndPageColumns': typeof import("../../app/components/containers/DndPageColumns.vue").default
  'ContainersDndSection': typeof import("../../app/components/containers/DndSection.vue").default
  'ContainersProductLinkButtonContainer': typeof import("../../app/components/containers/ProductLinkButtonContainer.vue").default
  'CreatureTypesCreatureTypeListItem': typeof import("../../app/components/creature-types/CreatureTypeListItem.vue").default
  'CreditsList': typeof import("../../app/components/credits/CreditsList.vue").default
  'CreditsListItem': typeof import("../../app/components/credits/CreditsListItem.vue").default
  'DndAbilitiesBlock': typeof import("../../app/components/dnd/AbilitiesBlock.vue").default
  'DndStatBlock': typeof import("../../app/components/dnd/StatBlock.vue").default
  'FiltersFilterPanel': typeof import("../../app/components/filters/FilterPanel.vue").default
  'HeadingsDndHeading': typeof import("../../app/components/headings/DndHeading.vue").default
  'ItemsItemView': typeof import("../../app/components/items/ItemView.vue").default
  'LabelsAlignmentLabel': typeof import("../../app/components/labels/AlignmentLabel.vue").default
  'LabelsChallengeRatingLabel': typeof import("../../app/components/labels/ChallengeRatingLabel.vue").default
  'LabelsDateLabel': typeof import("../../app/components/labels/DateLabel.vue").default
  'LabelsInlineLabel': typeof import("../../app/components/labels/InlineLabel.vue").default
  'LabelsLabelBase': typeof import("../../app/components/labels/LabelBase.vue").default
  'LabelsMagicSchoolLabel': typeof import("../../app/components/labels/MagicSchoolLabel.vue").default
  'LabelsMagicSchoolSpellbookLabel': typeof import("../../app/components/labels/MagicSchoolSpellbookLabel.vue").default
  'LabelsPageTitle': typeof import("../../app/components/labels/PageTitle.vue").default
  'LabelsPersonLabel': typeof import("../../app/components/labels/PersonLabel.vue").default
  'LabelsSavingThrowLabel': typeof import("../../app/components/labels/SavingThrowLabel.vue").default
  'LabelsSourceBindingLabel': typeof import("../../app/components/labels/SourceBindingLabel.vue").default
  'LabelsSourceFormatLabel': typeof import("../../app/components/labels/SourceFormatLabel.vue").default
  'LabelsSourceIsbnLabel': typeof import("../../app/components/labels/SourceIsbnLabel.vue").default
  'LabelsSourcePagesLabel': typeof import("../../app/components/labels/SourcePagesLabel.vue").default
  'LabelsSourceShortNameLabel': typeof import("../../app/components/labels/SourceShortNameLabel.vue").default
  'LabelsSpellComponentsLabel': typeof import("../../app/components/labels/SpellComponentsLabel.vue").default
  'ListsClassesLevelsList': typeof import("../../app/components/lists/ClassesLevelsList.vue").default
  'ListsDefinitionList': typeof import("../../app/components/lists/DefinitionList.vue").default
  'ListsDefinitionListItem': typeof import("../../app/components/lists/DefinitionListItem.vue").default
  'ListsDndListItem': typeof import("../../app/components/lists/DndListItem.vue").default
  'ListsLinkList': typeof import("../../app/components/lists/LinkList.vue").default
  'ListsListItemSkeleton': typeof import("../../app/components/lists/ListItemSkeleton.vue").default
  'ListsProductList': typeof import("../../app/components/lists/ProductList.vue").default
  'ListsProductListItem': typeof import("../../app/components/lists/ProductListItem.vue").default
  'ListsSinglePageList': typeof import("../../app/components/lists/SinglePageList.vue").default
  'ListsReferencesReferenceList': typeof import("../../app/components/lists/references/ReferenceList.vue").default
  'ListsReferencesReferenceListItem': typeof import("../../app/components/lists/references/ReferenceListItem.vue").default
  'LoadingProseSkeleton': typeof import("../../app/components/loading/ProseSkeleton.vue").default
  'MagicSchoolsMagicSchoolImage': typeof import("../../app/components/magic-schools/MagicSchoolImage.vue").default
  'MagicSchoolsMagicSchoolListItem': typeof import("../../app/components/magic-schools/MagicSchoolListItem.vue").default
  'MagicSchoolsMagicSchoolTeaser': typeof import("../../app/components/magic-schools/MagicSchoolTeaser.vue").default
  'MediaCoverImage': typeof import("../../app/components/media/CoverImage.vue").default
  'MediaImage': typeof import("../../app/components/media/MediaImage.vue").default
  'MediaPlaceholder': typeof import("../../app/components/media/MediaPlaceholder.vue").default
  'MovementSpeedsLabel': typeof import("../../app/components/movement/MovementSpeedsLabel.vue").default
  'NavigationBottomNavigation': typeof import("../../app/components/navigation/BottomNavigation.vue").default
  'NavigationBottomNavigationEditions': typeof import("../../app/components/navigation/BottomNavigationEditions.vue").default
  'NavigationEditionTabs': typeof import("../../app/components/navigation/EditionTabs.vue").default
  'NavigationMainNavigation': typeof import("../../app/components/navigation/MainNavigation.vue").default
  'PopoversPopoverBase': typeof import("../../app/components/popovers/PopoverBase.vue").default
  'PopoversPopoverCreatureType': typeof import("../../app/components/popovers/PopoverCreatureType.vue").default
  'SearchDndSearch': typeof import("../../app/components/search/DndSearch.vue").default
  'SourcesSourceCredits': typeof import("../../app/components/sources/SourceCredits.vue").default
  'SourcesSourceDetailsList': typeof import("../../app/components/sources/SourceDetailsList.vue").default
  'SourcesSourceTeaser': typeof import("../../app/components/sources/SourceTeaser.vue").default
  'SourcesSourcebookContents': typeof import("../../app/components/sources/SourcebookContents.vue").default
  'SourcesSourcebookDetailsListDefinition': typeof import("../../app/components/sources/SourcebookDetailsListDefinition.vue").default
  'SourcesSourcebookDetailsListTitle': typeof import("../../app/components/sources/SourcebookDetailsListTitle.vue").default
  'SourcesSourcebookInTheBox': typeof import("../../app/components/sources/SourcebookInTheBox.vue").default
  'SpellsSpell': typeof import("../../app/components/spells/Spell.vue").default
  'SpellsSpellbookExtra': typeof import("../../app/components/spells/SpellbookExtra.vue").default
  'SpellsSpellbookImage': typeof import("../../app/components/spells/SpellbookImage.vue").default
  'StripsEditionStrip': typeof import("../../app/components/strips/EditionStrip.vue").default
  'TabsTabBase': typeof import("../../app/components/tabs/TabBase.vue").default
  'TeasersSpellTeaser': typeof import("../../app/components/teasers/SpellTeaser.vue").default
  'TeasersSpellTeaserTile': typeof import("../../app/components/teasers/SpellTeaserTile.vue").default
  'TeasersTeaserGrid': typeof import("../../app/components/teasers/TeaserGrid.vue").default
  'TeasersTeaserTile': typeof import("../../app/components/teasers/TeaserTile.vue").default
  'TeasersTeaserTitle': typeof import("../../app/components/teasers/TeaserTitle.vue").default
  'TextProseContainer': typeof import("../../app/components/text/ProseContainer.vue").default
  'UColorModeAvatar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeAvatar.vue").default
  'UColorModeButton': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue").default
  'UColorModeImage': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeImage.vue").default
  'UColorModeSelect': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSelect.vue").default
  'UColorModeSwitch': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSwitch.vue").default
  'UAccordion': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue").default
  'UAlert': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Alert.vue").default
  'UApp': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/App.vue").default
  'UAuthForm': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue").default
  'UAvatar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue").default
  'UAvatarGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.vue").default
  'UBadge': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue").default
  'UBanner': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Banner.vue").default
  'UBlogPost': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/BlogPost.vue").default
  'UBlogPosts': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/BlogPosts.vue").default
  'UBreadcrumb': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue").default
  'UButton': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue").default
  'UCalendar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue").default
  'UCard': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Card.vue").default
  'UCarousel': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue").default
  'UChangelogVersion': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersion.vue").default
  'UChangelogVersions': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersions.vue").default
  'UChatMessage': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatMessage.vue").default
  'UChatMessages': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatMessages.vue").default
  'UChatPalette': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPalette.vue").default
  'UChatPrompt': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPrompt.vue").default
  'UChatPromptSubmit': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPromptSubmit.vue").default
  'UCheckbox': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue").default
  'UCheckboxGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.vue").default
  'UChip': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Chip.vue").default
  'UCollapsible': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue").default
  'UColorPicker': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue").default
  'UCommandPalette': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue").default
  'UContainer': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Container.vue").default
  'UContextMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue").default
  'UContextMenuContent': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.vue").default
  'UDashboardGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue").default
  'UDashboardNavbar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue").default
  'UDashboardPanel': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue").default
  'UDashboardResizeHandle': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardResizeHandle.vue").default
  'UDashboardSearch': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearch.vue").default
  'UDashboardSearchButton': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearchButton.vue").default
  'UDashboardSidebar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue").default
  'UDashboardSidebarCollapse': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue").default
  'UDashboardSidebarToggle': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarToggle.vue").default
  'UDashboardToolbar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardToolbar.vue").default
  'UDrawer': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue").default
  'UDropdownMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue").default
  'UDropdownMenuContent': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.vue").default
  'UEditor': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Editor.vue").default
  'UEditorDragHandle': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/EditorDragHandle.vue").default
  'UEditorEmojiMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/EditorEmojiMenu.vue").default
  'UEditorMentionMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/EditorMentionMenu.vue").default
  'UEditorSuggestionMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/EditorSuggestionMenu.vue").default
  'UEditorToolbar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/EditorToolbar.vue").default
  'UEmpty': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Empty.vue").default
  'UError': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Error.vue").default
  'UFieldGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue").default
  'UFileUpload': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue").default
  'UFooter': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Footer.vue").default
  'UFooterColumns': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FooterColumns.vue").default
  'UForm': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Form.vue").default
  'UFormField': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue").default
  'UHeader': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Header.vue").default
  'UIcon': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Icon.vue").default
  'UInput': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue").default
  'UInputDate': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputDate.vue").default
  'UInputMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue").default
  'UInputNumber': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue").default
  'UInputTags': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTags.vue").default
  'UInputTime': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTime.vue").default
  'UKbd': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue").default
  'ULink': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Link.vue").default
  'ULinkBase': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue").default
  'UMain': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Main.vue").default
  'UMarquee': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Marquee.vue").default
  'UModal': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue").default
  'UNavigationMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue").default
  'UOverlayProvider': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.vue").default
  'UPage': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Page.vue").default
  'UPageAnchors': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageAnchors.vue").default
  'UPageAside': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageAside.vue").default
  'UPageBody': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageBody.vue").default
  'UPageCTA': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageCTA.vue").default
  'UPageCard': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue").default
  'UPageColumns': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageColumns.vue").default
  'UPageFeature': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageFeature.vue").default
  'UPageGrid': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageGrid.vue").default
  'UPageHeader': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageHeader.vue").default
  'UPageHero': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageHero.vue").default
  'UPageLinks': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageLinks.vue").default
  'UPageList': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageList.vue").default
  'UPageLogos': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageLogos.vue").default
  'UPageSection': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageSection.vue").default
  'UPagination': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue").default
  'UPinInput': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PinInput.vue").default
  'UPopover': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Popover.vue").default
  'UPricingPlan': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingPlan.vue").default
  'UPricingPlans': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingPlans.vue").default
  'UPricingTable': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingTable.vue").default
  'UProgress': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue").default
  'URadioGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue").default
  'UScrollArea': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ScrollArea.vue").default
  'USelect': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Select.vue").default
  'USelectMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue").default
  'USeparator': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Separator.vue").default
  'USkeleton': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue").default
  'USlideover': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue").default
  'USlider': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slider.vue").default
  'UStepper': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue").default
  'USwitch': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue").default
  'UTable': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Table.vue").default
  'UTabs': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue").default
  'UTextarea': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue").default
  'UTimeline': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue").default
  'UToast': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toast.vue").default
  'UToaster': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toaster.vue").default
  'UTooltip': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue").default
  'UTree': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tree.vue").default
  'UUser': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/User.vue").default
  'ULocaleSelect': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/locale/LocaleSelect.vue").default
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only").default
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
  'NuxtImg': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default
  'NuxtPicture': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default
  'Icon': typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index").default
  'ColorScheme': typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue").default
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body
  'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default
  'LazyDiceRoll': LazyComponent<typeof import("../../app/components/DiceRoll.vue").default>
  'LazyDndHr': LazyComponent<typeof import("../../app/components/DndHr.vue").default>
  'LazyEditionSelector': LazyComponent<typeof import("../../app/components/EditionSelector.vue").default>
  'LazyBadgesBadgeBase': LazyComponent<typeof import("../../app/components/badges/BadgeBase.vue").default>
  'LazyBadgesBadgeContainer': LazyComponent<typeof import("../../app/components/badges/BadgeContainer.vue").default>
  'LazyBadgesCategoryBadge': LazyComponent<typeof import("../../app/components/badges/CategoryBadge.vue").default>
  'LazyBadgesGameEditionBadge': LazyComponent<typeof import("../../app/components/badges/GameEditionBadge.vue").default>
  'LazyBadgesPublicationTypeBadge': LazyComponent<typeof import("../../app/components/badges/PublicationTypeBadge.vue").default>
  'LazyButtonsBackButton': LazyComponent<typeof import("../../app/components/buttons/BackButton.vue").default>
  'LazyButtonsBaseButton': LazyComponent<typeof import("../../app/components/buttons/BaseButton.vue").default>
  'LazyButtonsEditionSelectorButton': LazyComponent<typeof import("../../app/components/buttons/EditionSelectorButton.vue").default>
  'LazyButtonsProductLinkButton': LazyComponent<typeof import("../../app/components/buttons/ProductLinkButton.vue").default>
  'LazyCampaignSettingsCampaignSettingCard': LazyComponent<typeof import("../../app/components/campaign-settings/CampaignSettingCard.vue").default>
  'LazyCampaignSettingsCampaignSettingListItem': LazyComponent<typeof import("../../app/components/campaign-settings/CampaignSettingListItem.vue").default>
  'LazyCampaignSettingsCampaignSettingTeaser': LazyComponent<typeof import("../../app/components/campaign-settings/CampaignSettingTeaser.vue").default>
  'LazyCardsBaseCard': LazyComponent<typeof import("../../app/components/cards/BaseCard.vue").default>
  'LazyCardsTabsCard': LazyComponent<typeof import("../../app/components/cards/TabsCard.vue").default>
  'LazyCharacterClassesCharacterClassTeaser': LazyComponent<typeof import("../../app/components/characterClasses/CharacterClassTeaser.vue").default>
  'LazyCharacterClassesPrestigeClassTeaser': LazyComponent<typeof import("../../app/components/characterClasses/PrestigeClassTeaser.vue").default>
  'LazyContainersDndPageColumns': LazyComponent<typeof import("../../app/components/containers/DndPageColumns.vue").default>
  'LazyContainersDndSection': LazyComponent<typeof import("../../app/components/containers/DndSection.vue").default>
  'LazyContainersProductLinkButtonContainer': LazyComponent<typeof import("../../app/components/containers/ProductLinkButtonContainer.vue").default>
  'LazyCreatureTypesCreatureTypeListItem': LazyComponent<typeof import("../../app/components/creature-types/CreatureTypeListItem.vue").default>
  'LazyCreditsList': LazyComponent<typeof import("../../app/components/credits/CreditsList.vue").default>
  'LazyCreditsListItem': LazyComponent<typeof import("../../app/components/credits/CreditsListItem.vue").default>
  'LazyDndAbilitiesBlock': LazyComponent<typeof import("../../app/components/dnd/AbilitiesBlock.vue").default>
  'LazyDndStatBlock': LazyComponent<typeof import("../../app/components/dnd/StatBlock.vue").default>
  'LazyFiltersFilterPanel': LazyComponent<typeof import("../../app/components/filters/FilterPanel.vue").default>
  'LazyHeadingsDndHeading': LazyComponent<typeof import("../../app/components/headings/DndHeading.vue").default>
  'LazyItemsItemView': LazyComponent<typeof import("../../app/components/items/ItemView.vue").default>
  'LazyLabelsAlignmentLabel': LazyComponent<typeof import("../../app/components/labels/AlignmentLabel.vue").default>
  'LazyLabelsChallengeRatingLabel': LazyComponent<typeof import("../../app/components/labels/ChallengeRatingLabel.vue").default>
  'LazyLabelsDateLabel': LazyComponent<typeof import("../../app/components/labels/DateLabel.vue").default>
  'LazyLabelsInlineLabel': LazyComponent<typeof import("../../app/components/labels/InlineLabel.vue").default>
  'LazyLabelsLabelBase': LazyComponent<typeof import("../../app/components/labels/LabelBase.vue").default>
  'LazyLabelsMagicSchoolLabel': LazyComponent<typeof import("../../app/components/labels/MagicSchoolLabel.vue").default>
  'LazyLabelsMagicSchoolSpellbookLabel': LazyComponent<typeof import("../../app/components/labels/MagicSchoolSpellbookLabel.vue").default>
  'LazyLabelsPageTitle': LazyComponent<typeof import("../../app/components/labels/PageTitle.vue").default>
  'LazyLabelsPersonLabel': LazyComponent<typeof import("../../app/components/labels/PersonLabel.vue").default>
  'LazyLabelsSavingThrowLabel': LazyComponent<typeof import("../../app/components/labels/SavingThrowLabel.vue").default>
  'LazyLabelsSourceBindingLabel': LazyComponent<typeof import("../../app/components/labels/SourceBindingLabel.vue").default>
  'LazyLabelsSourceFormatLabel': LazyComponent<typeof import("../../app/components/labels/SourceFormatLabel.vue").default>
  'LazyLabelsSourceIsbnLabel': LazyComponent<typeof import("../../app/components/labels/SourceIsbnLabel.vue").default>
  'LazyLabelsSourcePagesLabel': LazyComponent<typeof import("../../app/components/labels/SourcePagesLabel.vue").default>
  'LazyLabelsSourceShortNameLabel': LazyComponent<typeof import("../../app/components/labels/SourceShortNameLabel.vue").default>
  'LazyLabelsSpellComponentsLabel': LazyComponent<typeof import("../../app/components/labels/SpellComponentsLabel.vue").default>
  'LazyListsClassesLevelsList': LazyComponent<typeof import("../../app/components/lists/ClassesLevelsList.vue").default>
  'LazyListsDefinitionList': LazyComponent<typeof import("../../app/components/lists/DefinitionList.vue").default>
  'LazyListsDefinitionListItem': LazyComponent<typeof import("../../app/components/lists/DefinitionListItem.vue").default>
  'LazyListsDndListItem': LazyComponent<typeof import("../../app/components/lists/DndListItem.vue").default>
  'LazyListsLinkList': LazyComponent<typeof import("../../app/components/lists/LinkList.vue").default>
  'LazyListsListItemSkeleton': LazyComponent<typeof import("../../app/components/lists/ListItemSkeleton.vue").default>
  'LazyListsProductList': LazyComponent<typeof import("../../app/components/lists/ProductList.vue").default>
  'LazyListsProductListItem': LazyComponent<typeof import("../../app/components/lists/ProductListItem.vue").default>
  'LazyListsSinglePageList': LazyComponent<typeof import("../../app/components/lists/SinglePageList.vue").default>
  'LazyListsReferencesReferenceList': LazyComponent<typeof import("../../app/components/lists/references/ReferenceList.vue").default>
  'LazyListsReferencesReferenceListItem': LazyComponent<typeof import("../../app/components/lists/references/ReferenceListItem.vue").default>
  'LazyLoadingProseSkeleton': LazyComponent<typeof import("../../app/components/loading/ProseSkeleton.vue").default>
  'LazyMagicSchoolsMagicSchoolImage': LazyComponent<typeof import("../../app/components/magic-schools/MagicSchoolImage.vue").default>
  'LazyMagicSchoolsMagicSchoolListItem': LazyComponent<typeof import("../../app/components/magic-schools/MagicSchoolListItem.vue").default>
  'LazyMagicSchoolsMagicSchoolTeaser': LazyComponent<typeof import("../../app/components/magic-schools/MagicSchoolTeaser.vue").default>
  'LazyMediaCoverImage': LazyComponent<typeof import("../../app/components/media/CoverImage.vue").default>
  'LazyMediaImage': LazyComponent<typeof import("../../app/components/media/MediaImage.vue").default>
  'LazyMediaPlaceholder': LazyComponent<typeof import("../../app/components/media/MediaPlaceholder.vue").default>
  'LazyMovementSpeedsLabel': LazyComponent<typeof import("../../app/components/movement/MovementSpeedsLabel.vue").default>
  'LazyNavigationBottomNavigation': LazyComponent<typeof import("../../app/components/navigation/BottomNavigation.vue").default>
  'LazyNavigationBottomNavigationEditions': LazyComponent<typeof import("../../app/components/navigation/BottomNavigationEditions.vue").default>
  'LazyNavigationEditionTabs': LazyComponent<typeof import("../../app/components/navigation/EditionTabs.vue").default>
  'LazyNavigationMainNavigation': LazyComponent<typeof import("../../app/components/navigation/MainNavigation.vue").default>
  'LazyPopoversPopoverBase': LazyComponent<typeof import("../../app/components/popovers/PopoverBase.vue").default>
  'LazyPopoversPopoverCreatureType': LazyComponent<typeof import("../../app/components/popovers/PopoverCreatureType.vue").default>
  'LazySearchDndSearch': LazyComponent<typeof import("../../app/components/search/DndSearch.vue").default>
  'LazySourcesSourceCredits': LazyComponent<typeof import("../../app/components/sources/SourceCredits.vue").default>
  'LazySourcesSourceDetailsList': LazyComponent<typeof import("../../app/components/sources/SourceDetailsList.vue").default>
  'LazySourcesSourceTeaser': LazyComponent<typeof import("../../app/components/sources/SourceTeaser.vue").default>
  'LazySourcesSourcebookContents': LazyComponent<typeof import("../../app/components/sources/SourcebookContents.vue").default>
  'LazySourcesSourcebookDetailsListDefinition': LazyComponent<typeof import("../../app/components/sources/SourcebookDetailsListDefinition.vue").default>
  'LazySourcesSourcebookDetailsListTitle': LazyComponent<typeof import("../../app/components/sources/SourcebookDetailsListTitle.vue").default>
  'LazySourcesSourcebookInTheBox': LazyComponent<typeof import("../../app/components/sources/SourcebookInTheBox.vue").default>
  'LazySpellsSpell': LazyComponent<typeof import("../../app/components/spells/Spell.vue").default>
  'LazySpellsSpellbookExtra': LazyComponent<typeof import("../../app/components/spells/SpellbookExtra.vue").default>
  'LazySpellsSpellbookImage': LazyComponent<typeof import("../../app/components/spells/SpellbookImage.vue").default>
  'LazyStripsEditionStrip': LazyComponent<typeof import("../../app/components/strips/EditionStrip.vue").default>
  'LazyTabsTabBase': LazyComponent<typeof import("../../app/components/tabs/TabBase.vue").default>
  'LazyTeasersSpellTeaser': LazyComponent<typeof import("../../app/components/teasers/SpellTeaser.vue").default>
  'LazyTeasersSpellTeaserTile': LazyComponent<typeof import("../../app/components/teasers/SpellTeaserTile.vue").default>
  'LazyTeasersTeaserGrid': LazyComponent<typeof import("../../app/components/teasers/TeaserGrid.vue").default>
  'LazyTeasersTeaserTile': LazyComponent<typeof import("../../app/components/teasers/TeaserTile.vue").default>
  'LazyTeasersTeaserTitle': LazyComponent<typeof import("../../app/components/teasers/TeaserTitle.vue").default>
  'LazyTextProseContainer': LazyComponent<typeof import("../../app/components/text/ProseContainer.vue").default>
  'LazyUColorModeAvatar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeAvatar.vue").default>
  'LazyUColorModeButton': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue").default>
  'LazyUColorModeImage': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeImage.vue").default>
  'LazyUColorModeSelect': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSelect.vue").default>
  'LazyUColorModeSwitch': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSwitch.vue").default>
  'LazyUAccordion': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue").default>
  'LazyUAlert': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Alert.vue").default>
  'LazyUApp': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/App.vue").default>
  'LazyUAuthForm': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue").default>
  'LazyUAvatar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue").default>
  'LazyUAvatarGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.vue").default>
  'LazyUBadge': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue").default>
  'LazyUBanner': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Banner.vue").default>
  'LazyUBlogPost': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/BlogPost.vue").default>
  'LazyUBlogPosts': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/BlogPosts.vue").default>
  'LazyUBreadcrumb': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue").default>
  'LazyUButton': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue").default>
  'LazyUCalendar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue").default>
  'LazyUCard': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Card.vue").default>
  'LazyUCarousel': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue").default>
  'LazyUChangelogVersion': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersion.vue").default>
  'LazyUChangelogVersions': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersions.vue").default>
  'LazyUChatMessage': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatMessage.vue").default>
  'LazyUChatMessages': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatMessages.vue").default>
  'LazyUChatPalette': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPalette.vue").default>
  'LazyUChatPrompt': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPrompt.vue").default>
  'LazyUChatPromptSubmit': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ChatPromptSubmit.vue").default>
  'LazyUCheckbox': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue").default>
  'LazyUCheckboxGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.vue").default>
  'LazyUChip': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Chip.vue").default>
  'LazyUCollapsible': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue").default>
  'LazyUColorPicker': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue").default>
  'LazyUCommandPalette': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue").default>
  'LazyUContainer': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Container.vue").default>
  'LazyUContextMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue").default>
  'LazyUContextMenuContent': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.vue").default>
  'LazyUDashboardGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue").default>
  'LazyUDashboardNavbar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue").default>
  'LazyUDashboardPanel': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue").default>
  'LazyUDashboardResizeHandle': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardResizeHandle.vue").default>
  'LazyUDashboardSearch': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearch.vue").default>
  'LazyUDashboardSearchButton': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearchButton.vue").default>
  'LazyUDashboardSidebar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue").default>
  'LazyUDashboardSidebarCollapse': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue").default>
  'LazyUDashboardSidebarToggle': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarToggle.vue").default>
  'LazyUDashboardToolbar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DashboardToolbar.vue").default>
  'LazyUDrawer': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue").default>
  'LazyUDropdownMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue").default>
  'LazyUDropdownMenuContent': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.vue").default>
  'LazyUEditor': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Editor.vue").default>
  'LazyUEditorDragHandle': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/EditorDragHandle.vue").default>
  'LazyUEditorEmojiMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/EditorEmojiMenu.vue").default>
  'LazyUEditorMentionMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/EditorMentionMenu.vue").default>
  'LazyUEditorSuggestionMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/EditorSuggestionMenu.vue").default>
  'LazyUEditorToolbar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/EditorToolbar.vue").default>
  'LazyUEmpty': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Empty.vue").default>
  'LazyUError': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Error.vue").default>
  'LazyUFieldGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue").default>
  'LazyUFileUpload': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue").default>
  'LazyUFooter': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Footer.vue").default>
  'LazyUFooterColumns': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FooterColumns.vue").default>
  'LazyUForm': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Form.vue").default>
  'LazyUFormField': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue").default>
  'LazyUHeader': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Header.vue").default>
  'LazyUIcon': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Icon.vue").default>
  'LazyUInput': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue").default>
  'LazyUInputDate': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputDate.vue").default>
  'LazyUInputMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue").default>
  'LazyUInputNumber': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue").default>
  'LazyUInputTags': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTags.vue").default>
  'LazyUInputTime': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTime.vue").default>
  'LazyUKbd': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue").default>
  'LazyULink': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Link.vue").default>
  'LazyULinkBase': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue").default>
  'LazyUMain': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Main.vue").default>
  'LazyUMarquee': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Marquee.vue").default>
  'LazyUModal': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue").default>
  'LazyUNavigationMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue").default>
  'LazyUOverlayProvider': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.vue").default>
  'LazyUPage': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Page.vue").default>
  'LazyUPageAnchors': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageAnchors.vue").default>
  'LazyUPageAside': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageAside.vue").default>
  'LazyUPageBody': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageBody.vue").default>
  'LazyUPageCTA': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageCTA.vue").default>
  'LazyUPageCard': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue").default>
  'LazyUPageColumns': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageColumns.vue").default>
  'LazyUPageFeature': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageFeature.vue").default>
  'LazyUPageGrid': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageGrid.vue").default>
  'LazyUPageHeader': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageHeader.vue").default>
  'LazyUPageHero': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageHero.vue").default>
  'LazyUPageLinks': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageLinks.vue").default>
  'LazyUPageList': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageList.vue").default>
  'LazyUPageLogos': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageLogos.vue").default>
  'LazyUPageSection': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PageSection.vue").default>
  'LazyUPagination': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue").default>
  'LazyUPinInput': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PinInput.vue").default>
  'LazyUPopover': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Popover.vue").default>
  'LazyUPricingPlan': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingPlan.vue").default>
  'LazyUPricingPlans': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingPlans.vue").default>
  'LazyUPricingTable': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PricingTable.vue").default>
  'LazyUProgress': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue").default>
  'LazyURadioGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue").default>
  'LazyUScrollArea': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ScrollArea.vue").default>
  'LazyUSelect': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Select.vue").default>
  'LazyUSelectMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue").default>
  'LazyUSeparator': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Separator.vue").default>
  'LazyUSkeleton': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue").default>
  'LazyUSlideover': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue").default>
  'LazyUSlider': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slider.vue").default>
  'LazyUStepper': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue").default>
  'LazyUSwitch': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue").default>
  'LazyUTable': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Table.vue").default>
  'LazyUTabs': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue").default>
  'LazyUTextarea': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue").default>
  'LazyUTimeline': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue").default>
  'LazyUToast': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toast.vue").default>
  'LazyUToaster': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toaster.vue").default>
  'LazyUTooltip': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue").default>
  'LazyUTree': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tree.vue").default>
  'LazyUUser': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/User.vue").default>
  'LazyULocaleSelect': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/locale/LocaleSelect.vue").default>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only").default>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default>
  'LazyIcon': LazyComponent<typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index").default>
  'LazyColorScheme': LazyComponent<typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue").default>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
