
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const DiceRoll: typeof import("../app/components/DiceRoll.vue").default
export const DndHr: typeof import("../app/components/DndHr.vue").default
export const EditionSelector: typeof import("../app/components/EditionSelector.vue").default
export const BadgesBadgeBase: typeof import("../app/components/badges/BadgeBase.vue").default
export const BadgesBadgeContainer: typeof import("../app/components/badges/BadgeContainer.vue").default
export const BadgesCategoryBadge: typeof import("../app/components/badges/CategoryBadge.vue").default
export const BadgesGameEditionBadge: typeof import("../app/components/badges/GameEditionBadge.vue").default
export const BadgesPublicationTypeBadge: typeof import("../app/components/badges/PublicationTypeBadge.vue").default
export const ButtonsBackButton: typeof import("../app/components/buttons/BackButton.vue").default
export const ButtonsBaseButton: typeof import("../app/components/buttons/BaseButton.vue").default
export const ButtonsEditionSelectorButton: typeof import("../app/components/buttons/EditionSelectorButton.vue").default
export const ButtonsProductLinkButton: typeof import("../app/components/buttons/ProductLinkButton.vue").default
export const CampaignSettingsCampaignSettingCard: typeof import("../app/components/campaign-settings/CampaignSettingCard.vue").default
export const CampaignSettingsCampaignSettingListItem: typeof import("../app/components/campaign-settings/CampaignSettingListItem.vue").default
export const CampaignSettingsCampaignSettingTeaser: typeof import("../app/components/campaign-settings/CampaignSettingTeaser.vue").default
export const CardsBaseCard: typeof import("../app/components/cards/BaseCard.vue").default
export const CardsTabsCard: typeof import("../app/components/cards/TabsCard.vue").default
export const CharacterClassesCharacterClassTeaser: typeof import("../app/components/characterClasses/CharacterClassTeaser.vue").default
export const CharacterClassesPrestigeClassTeaser: typeof import("../app/components/characterClasses/PrestigeClassTeaser.vue").default
export const ContainersDndPageColumns: typeof import("../app/components/containers/DndPageColumns.vue").default
export const ContainersDndSection: typeof import("../app/components/containers/DndSection.vue").default
export const ContainersProductLinkButtonContainer: typeof import("../app/components/containers/ProductLinkButtonContainer.vue").default
export const CreatureTypesCreatureTypeListItem: typeof import("../app/components/creature-types/CreatureTypeListItem.vue").default
export const CreditsList: typeof import("../app/components/credits/CreditsList.vue").default
export const CreditsListItem: typeof import("../app/components/credits/CreditsListItem.vue").default
export const DndAbilitiesBlock: typeof import("../app/components/dnd/AbilitiesBlock.vue").default
export const DndStatBlock: typeof import("../app/components/dnd/StatBlock.vue").default
export const FiltersFilterPanel: typeof import("../app/components/filters/FilterPanel.vue").default
export const HeadingsDndHeading: typeof import("../app/components/headings/DndHeading.vue").default
export const ItemsItemView: typeof import("../app/components/items/ItemView.vue").default
export const LabelsAlignmentLabel: typeof import("../app/components/labels/AlignmentLabel.vue").default
export const LabelsChallengeRatingLabel: typeof import("../app/components/labels/ChallengeRatingLabel.vue").default
export const LabelsDateLabel: typeof import("../app/components/labels/DateLabel.vue").default
export const LabelsInlineLabel: typeof import("../app/components/labels/InlineLabel.vue").default
export const LabelsLabelBase: typeof import("../app/components/labels/LabelBase.vue").default
export const LabelsMagicSchoolLabel: typeof import("../app/components/labels/MagicSchoolLabel.vue").default
export const LabelsMagicSchoolSpellbookLabel: typeof import("../app/components/labels/MagicSchoolSpellbookLabel.vue").default
export const LabelsPageTitle: typeof import("../app/components/labels/PageTitle.vue").default
export const LabelsPersonLabel: typeof import("../app/components/labels/PersonLabel.vue").default
export const LabelsSavingThrowLabel: typeof import("../app/components/labels/SavingThrowLabel.vue").default
export const LabelsSourceBindingLabel: typeof import("../app/components/labels/SourceBindingLabel.vue").default
export const LabelsSourceFormatLabel: typeof import("../app/components/labels/SourceFormatLabel.vue").default
export const LabelsSourceIsbnLabel: typeof import("../app/components/labels/SourceIsbnLabel.vue").default
export const LabelsSourcePagesLabel: typeof import("../app/components/labels/SourcePagesLabel.vue").default
export const LabelsSourceShortNameLabel: typeof import("../app/components/labels/SourceShortNameLabel.vue").default
export const LabelsSpellComponentsLabel: typeof import("../app/components/labels/SpellComponentsLabel.vue").default
export const ListsClassesLevelsList: typeof import("../app/components/lists/ClassesLevelsList.vue").default
export const ListsDefinitionList: typeof import("../app/components/lists/DefinitionList.vue").default
export const ListsDefinitionListItem: typeof import("../app/components/lists/DefinitionListItem.vue").default
export const ListsDndListItem: typeof import("../app/components/lists/DndListItem.vue").default
export const ListsLinkList: typeof import("../app/components/lists/LinkList.vue").default
export const ListsListItemSkeleton: typeof import("../app/components/lists/ListItemSkeleton.vue").default
export const ListsProductList: typeof import("../app/components/lists/ProductList.vue").default
export const ListsProductListItem: typeof import("../app/components/lists/ProductListItem.vue").default
export const ListsSinglePageList: typeof import("../app/components/lists/SinglePageList.vue").default
export const ListsReferencesReferenceList: typeof import("../app/components/lists/references/ReferenceList.vue").default
export const ListsReferencesReferenceListItem: typeof import("../app/components/lists/references/ReferenceListItem.vue").default
export const LoadingProseSkeleton: typeof import("../app/components/loading/ProseSkeleton.vue").default
export const MagicSchoolsMagicSchoolImage: typeof import("../app/components/magic-schools/MagicSchoolImage.vue").default
export const MagicSchoolsMagicSchoolListItem: typeof import("../app/components/magic-schools/MagicSchoolListItem.vue").default
export const MagicSchoolsMagicSchoolTeaser: typeof import("../app/components/magic-schools/MagicSchoolTeaser.vue").default
export const MediaCoverImage: typeof import("../app/components/media/CoverImage.vue").default
export const MediaImage: typeof import("../app/components/media/MediaImage.vue").default
export const MediaPlaceholder: typeof import("../app/components/media/MediaPlaceholder.vue").default
export const MovementSpeedsLabel: typeof import("../app/components/movement/MovementSpeedsLabel.vue").default
export const NavigationBottomNavigation: typeof import("../app/components/navigation/BottomNavigation.vue").default
export const NavigationBottomNavigationEditions: typeof import("../app/components/navigation/BottomNavigationEditions.vue").default
export const NavigationEditionTabs: typeof import("../app/components/navigation/EditionTabs.vue").default
export const NavigationMainNavigation: typeof import("../app/components/navigation/MainNavigation.vue").default
export const PopoversPopoverBase: typeof import("../app/components/popovers/PopoverBase.vue").default
export const PopoversPopoverCreatureType: typeof import("../app/components/popovers/PopoverCreatureType.vue").default
export const SearchDndSearch: typeof import("../app/components/search/DndSearch.vue").default
export const SourcesSourceCredits: typeof import("../app/components/sources/SourceCredits.vue").default
export const SourcesSourceDetailsList: typeof import("../app/components/sources/SourceDetailsList.vue").default
export const SourcesSourceTeaser: typeof import("../app/components/sources/SourceTeaser.vue").default
export const SourcesSourcebookContents: typeof import("../app/components/sources/SourcebookContents.vue").default
export const SourcesSourcebookDetailsListDefinition: typeof import("../app/components/sources/SourcebookDetailsListDefinition.vue").default
export const SourcesSourcebookDetailsListTitle: typeof import("../app/components/sources/SourcebookDetailsListTitle.vue").default
export const SourcesSourcebookInTheBox: typeof import("../app/components/sources/SourcebookInTheBox.vue").default
export const SpellsSpell: typeof import("../app/components/spells/Spell.vue").default
export const SpellsSpellbookExtra: typeof import("../app/components/spells/SpellbookExtra.vue").default
export const SpellsSpellbookImage: typeof import("../app/components/spells/SpellbookImage.vue").default
export const StripsEditionStrip: typeof import("../app/components/strips/EditionStrip.vue").default
export const TabsTabBase: typeof import("../app/components/tabs/TabBase.vue").default
export const TeasersSpellTeaser: typeof import("../app/components/teasers/SpellTeaser.vue").default
export const TeasersSpellTeaserTile: typeof import("../app/components/teasers/SpellTeaserTile.vue").default
export const TeasersTeaserGrid: typeof import("../app/components/teasers/TeaserGrid.vue").default
export const TeasersTeaserTile: typeof import("../app/components/teasers/TeaserTile.vue").default
export const TeasersTeaserTitle: typeof import("../app/components/teasers/TeaserTitle.vue").default
export const TextProseContainer: typeof import("../app/components/text/ProseContainer.vue").default
export const UColorModeAvatar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeAvatar.vue").default
export const UColorModeButton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue").default
export const UColorModeImage: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeImage.vue").default
export const UColorModeSelect: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSelect.vue").default
export const UColorModeSwitch: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSwitch.vue").default
export const UAccordion: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue").default
export const UAlert: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Alert.vue").default
export const UApp: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/App.vue").default
export const UAuthForm: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue").default
export const UAvatar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue").default
export const UAvatarGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.vue").default
export const UBadge: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue").default
export const UBanner: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Banner.vue").default
export const UBlogPost: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/BlogPost.vue").default
export const UBlogPosts: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/BlogPosts.vue").default
export const UBreadcrumb: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue").default
export const UButton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Button.vue").default
export const UCalendar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue").default
export const UCard: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Card.vue").default
export const UCarousel: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue").default
export const UChangelogVersion: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersion.vue").default
export const UChangelogVersions: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersions.vue").default
export const UChatMessage: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ChatMessage.vue").default
export const UChatMessages: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ChatMessages.vue").default
export const UChatPalette: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ChatPalette.vue").default
export const UChatPrompt: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ChatPrompt.vue").default
export const UChatPromptSubmit: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ChatPromptSubmit.vue").default
export const UCheckbox: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue").default
export const UCheckboxGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.vue").default
export const UChip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Chip.vue").default
export const UCollapsible: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue").default
export const UColorPicker: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue").default
export const UCommandPalette: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue").default
export const UContainer: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Container.vue").default
export const UContextMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue").default
export const UContextMenuContent: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.vue").default
export const UDashboardGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue").default
export const UDashboardNavbar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue").default
export const UDashboardPanel: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue").default
export const UDashboardResizeHandle: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DashboardResizeHandle.vue").default
export const UDashboardSearch: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearch.vue").default
export const UDashboardSearchButton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearchButton.vue").default
export const UDashboardSidebar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue").default
export const UDashboardSidebarCollapse: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue").default
export const UDashboardSidebarToggle: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarToggle.vue").default
export const UDashboardToolbar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DashboardToolbar.vue").default
export const UDrawer: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue").default
export const UDropdownMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue").default
export const UDropdownMenuContent: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.vue").default
export const UEditor: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Editor.vue").default
export const UEditorDragHandle: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/EditorDragHandle.vue").default
export const UEditorEmojiMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/EditorEmojiMenu.vue").default
export const UEditorMentionMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/EditorMentionMenu.vue").default
export const UEditorSuggestionMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/EditorSuggestionMenu.vue").default
export const UEditorToolbar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/EditorToolbar.vue").default
export const UEmpty: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Empty.vue").default
export const UError: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Error.vue").default
export const UFieldGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue").default
export const UFileUpload: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue").default
export const UFooter: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Footer.vue").default
export const UFooterColumns: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/FooterColumns.vue").default
export const UForm: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Form.vue").default
export const UFormField: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue").default
export const UHeader: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Header.vue").default
export const UIcon: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Icon.vue").default
export const UInput: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Input.vue").default
export const UInputDate: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputDate.vue").default
export const UInputMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue").default
export const UInputNumber: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue").default
export const UInputTags: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputTags.vue").default
export const UInputTime: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputTime.vue").default
export const UKbd: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue").default
export const ULink: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Link.vue").default
export const ULinkBase: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue").default
export const UMain: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Main.vue").default
export const UMarquee: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Marquee.vue").default
export const UModal: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue").default
export const UNavigationMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue").default
export const UOverlayProvider: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.vue").default
export const UPage: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Page.vue").default
export const UPageAnchors: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageAnchors.vue").default
export const UPageAside: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageAside.vue").default
export const UPageBody: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageBody.vue").default
export const UPageCTA: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageCTA.vue").default
export const UPageCard: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue").default
export const UPageColumns: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageColumns.vue").default
export const UPageFeature: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageFeature.vue").default
export const UPageGrid: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageGrid.vue").default
export const UPageHeader: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageHeader.vue").default
export const UPageHero: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageHero.vue").default
export const UPageLinks: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageLinks.vue").default
export const UPageList: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageList.vue").default
export const UPageLogos: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageLogos.vue").default
export const UPageSection: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageSection.vue").default
export const UPagination: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue").default
export const UPinInput: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PinInput.vue").default
export const UPopover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Popover.vue").default
export const UPricingPlan: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PricingPlan.vue").default
export const UPricingPlans: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PricingPlans.vue").default
export const UPricingTable: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PricingTable.vue").default
export const UProgress: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue").default
export const URadioGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue").default
export const UScrollArea: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ScrollArea.vue").default
export const USelect: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Select.vue").default
export const USelectMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue").default
export const USeparator: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Separator.vue").default
export const USkeleton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue").default
export const USlideover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue").default
export const USlider: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Slider.vue").default
export const UStepper: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue").default
export const USwitch: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue").default
export const UTable: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Table.vue").default
export const UTabs: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue").default
export const UTextarea: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue").default
export const UTimeline: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue").default
export const UToast: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Toast.vue").default
export const UToaster: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Toaster.vue").default
export const UTooltip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue").default
export const UTree: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Tree.vue").default
export const UUser: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/User.vue").default
export const ULocaleSelect: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/locale/LocaleSelect.vue").default
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue").default
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout").default
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only").default
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only").default
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder").default
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link").default
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default
export const Icon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index").default
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue").default
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page").default
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components").NoScript
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components").Link
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components").Base
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components").Title
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components").Meta
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components").Style
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components").Head
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components").Html
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components").Body
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island").default
export const LazyDiceRoll: LazyComponent<typeof import("../app/components/DiceRoll.vue").default>
export const LazyDndHr: LazyComponent<typeof import("../app/components/DndHr.vue").default>
export const LazyEditionSelector: LazyComponent<typeof import("../app/components/EditionSelector.vue").default>
export const LazyBadgesBadgeBase: LazyComponent<typeof import("../app/components/badges/BadgeBase.vue").default>
export const LazyBadgesBadgeContainer: LazyComponent<typeof import("../app/components/badges/BadgeContainer.vue").default>
export const LazyBadgesCategoryBadge: LazyComponent<typeof import("../app/components/badges/CategoryBadge.vue").default>
export const LazyBadgesGameEditionBadge: LazyComponent<typeof import("../app/components/badges/GameEditionBadge.vue").default>
export const LazyBadgesPublicationTypeBadge: LazyComponent<typeof import("../app/components/badges/PublicationTypeBadge.vue").default>
export const LazyButtonsBackButton: LazyComponent<typeof import("../app/components/buttons/BackButton.vue").default>
export const LazyButtonsBaseButton: LazyComponent<typeof import("../app/components/buttons/BaseButton.vue").default>
export const LazyButtonsEditionSelectorButton: LazyComponent<typeof import("../app/components/buttons/EditionSelectorButton.vue").default>
export const LazyButtonsProductLinkButton: LazyComponent<typeof import("../app/components/buttons/ProductLinkButton.vue").default>
export const LazyCampaignSettingsCampaignSettingCard: LazyComponent<typeof import("../app/components/campaign-settings/CampaignSettingCard.vue").default>
export const LazyCampaignSettingsCampaignSettingListItem: LazyComponent<typeof import("../app/components/campaign-settings/CampaignSettingListItem.vue").default>
export const LazyCampaignSettingsCampaignSettingTeaser: LazyComponent<typeof import("../app/components/campaign-settings/CampaignSettingTeaser.vue").default>
export const LazyCardsBaseCard: LazyComponent<typeof import("../app/components/cards/BaseCard.vue").default>
export const LazyCardsTabsCard: LazyComponent<typeof import("../app/components/cards/TabsCard.vue").default>
export const LazyCharacterClassesCharacterClassTeaser: LazyComponent<typeof import("../app/components/characterClasses/CharacterClassTeaser.vue").default>
export const LazyCharacterClassesPrestigeClassTeaser: LazyComponent<typeof import("../app/components/characterClasses/PrestigeClassTeaser.vue").default>
export const LazyContainersDndPageColumns: LazyComponent<typeof import("../app/components/containers/DndPageColumns.vue").default>
export const LazyContainersDndSection: LazyComponent<typeof import("../app/components/containers/DndSection.vue").default>
export const LazyContainersProductLinkButtonContainer: LazyComponent<typeof import("../app/components/containers/ProductLinkButtonContainer.vue").default>
export const LazyCreatureTypesCreatureTypeListItem: LazyComponent<typeof import("../app/components/creature-types/CreatureTypeListItem.vue").default>
export const LazyCreditsList: LazyComponent<typeof import("../app/components/credits/CreditsList.vue").default>
export const LazyCreditsListItem: LazyComponent<typeof import("../app/components/credits/CreditsListItem.vue").default>
export const LazyDndAbilitiesBlock: LazyComponent<typeof import("../app/components/dnd/AbilitiesBlock.vue").default>
export const LazyDndStatBlock: LazyComponent<typeof import("../app/components/dnd/StatBlock.vue").default>
export const LazyFiltersFilterPanel: LazyComponent<typeof import("../app/components/filters/FilterPanel.vue").default>
export const LazyHeadingsDndHeading: LazyComponent<typeof import("../app/components/headings/DndHeading.vue").default>
export const LazyItemsItemView: LazyComponent<typeof import("../app/components/items/ItemView.vue").default>
export const LazyLabelsAlignmentLabel: LazyComponent<typeof import("../app/components/labels/AlignmentLabel.vue").default>
export const LazyLabelsChallengeRatingLabel: LazyComponent<typeof import("../app/components/labels/ChallengeRatingLabel.vue").default>
export const LazyLabelsDateLabel: LazyComponent<typeof import("../app/components/labels/DateLabel.vue").default>
export const LazyLabelsInlineLabel: LazyComponent<typeof import("../app/components/labels/InlineLabel.vue").default>
export const LazyLabelsLabelBase: LazyComponent<typeof import("../app/components/labels/LabelBase.vue").default>
export const LazyLabelsMagicSchoolLabel: LazyComponent<typeof import("../app/components/labels/MagicSchoolLabel.vue").default>
export const LazyLabelsMagicSchoolSpellbookLabel: LazyComponent<typeof import("../app/components/labels/MagicSchoolSpellbookLabel.vue").default>
export const LazyLabelsPageTitle: LazyComponent<typeof import("../app/components/labels/PageTitle.vue").default>
export const LazyLabelsPersonLabel: LazyComponent<typeof import("../app/components/labels/PersonLabel.vue").default>
export const LazyLabelsSavingThrowLabel: LazyComponent<typeof import("../app/components/labels/SavingThrowLabel.vue").default>
export const LazyLabelsSourceBindingLabel: LazyComponent<typeof import("../app/components/labels/SourceBindingLabel.vue").default>
export const LazyLabelsSourceFormatLabel: LazyComponent<typeof import("../app/components/labels/SourceFormatLabel.vue").default>
export const LazyLabelsSourceIsbnLabel: LazyComponent<typeof import("../app/components/labels/SourceIsbnLabel.vue").default>
export const LazyLabelsSourcePagesLabel: LazyComponent<typeof import("../app/components/labels/SourcePagesLabel.vue").default>
export const LazyLabelsSourceShortNameLabel: LazyComponent<typeof import("../app/components/labels/SourceShortNameLabel.vue").default>
export const LazyLabelsSpellComponentsLabel: LazyComponent<typeof import("../app/components/labels/SpellComponentsLabel.vue").default>
export const LazyListsClassesLevelsList: LazyComponent<typeof import("../app/components/lists/ClassesLevelsList.vue").default>
export const LazyListsDefinitionList: LazyComponent<typeof import("../app/components/lists/DefinitionList.vue").default>
export const LazyListsDefinitionListItem: LazyComponent<typeof import("../app/components/lists/DefinitionListItem.vue").default>
export const LazyListsDndListItem: LazyComponent<typeof import("../app/components/lists/DndListItem.vue").default>
export const LazyListsLinkList: LazyComponent<typeof import("../app/components/lists/LinkList.vue").default>
export const LazyListsListItemSkeleton: LazyComponent<typeof import("../app/components/lists/ListItemSkeleton.vue").default>
export const LazyListsProductList: LazyComponent<typeof import("../app/components/lists/ProductList.vue").default>
export const LazyListsProductListItem: LazyComponent<typeof import("../app/components/lists/ProductListItem.vue").default>
export const LazyListsSinglePageList: LazyComponent<typeof import("../app/components/lists/SinglePageList.vue").default>
export const LazyListsReferencesReferenceList: LazyComponent<typeof import("../app/components/lists/references/ReferenceList.vue").default>
export const LazyListsReferencesReferenceListItem: LazyComponent<typeof import("../app/components/lists/references/ReferenceListItem.vue").default>
export const LazyLoadingProseSkeleton: LazyComponent<typeof import("../app/components/loading/ProseSkeleton.vue").default>
export const LazyMagicSchoolsMagicSchoolImage: LazyComponent<typeof import("../app/components/magic-schools/MagicSchoolImage.vue").default>
export const LazyMagicSchoolsMagicSchoolListItem: LazyComponent<typeof import("../app/components/magic-schools/MagicSchoolListItem.vue").default>
export const LazyMagicSchoolsMagicSchoolTeaser: LazyComponent<typeof import("../app/components/magic-schools/MagicSchoolTeaser.vue").default>
export const LazyMediaCoverImage: LazyComponent<typeof import("../app/components/media/CoverImage.vue").default>
export const LazyMediaImage: LazyComponent<typeof import("../app/components/media/MediaImage.vue").default>
export const LazyMediaPlaceholder: LazyComponent<typeof import("../app/components/media/MediaPlaceholder.vue").default>
export const LazyMovementSpeedsLabel: LazyComponent<typeof import("../app/components/movement/MovementSpeedsLabel.vue").default>
export const LazyNavigationBottomNavigation: LazyComponent<typeof import("../app/components/navigation/BottomNavigation.vue").default>
export const LazyNavigationBottomNavigationEditions: LazyComponent<typeof import("../app/components/navigation/BottomNavigationEditions.vue").default>
export const LazyNavigationEditionTabs: LazyComponent<typeof import("../app/components/navigation/EditionTabs.vue").default>
export const LazyNavigationMainNavigation: LazyComponent<typeof import("../app/components/navigation/MainNavigation.vue").default>
export const LazyPopoversPopoverBase: LazyComponent<typeof import("../app/components/popovers/PopoverBase.vue").default>
export const LazyPopoversPopoverCreatureType: LazyComponent<typeof import("../app/components/popovers/PopoverCreatureType.vue").default>
export const LazySearchDndSearch: LazyComponent<typeof import("../app/components/search/DndSearch.vue").default>
export const LazySourcesSourceCredits: LazyComponent<typeof import("../app/components/sources/SourceCredits.vue").default>
export const LazySourcesSourceDetailsList: LazyComponent<typeof import("../app/components/sources/SourceDetailsList.vue").default>
export const LazySourcesSourceTeaser: LazyComponent<typeof import("../app/components/sources/SourceTeaser.vue").default>
export const LazySourcesSourcebookContents: LazyComponent<typeof import("../app/components/sources/SourcebookContents.vue").default>
export const LazySourcesSourcebookDetailsListDefinition: LazyComponent<typeof import("../app/components/sources/SourcebookDetailsListDefinition.vue").default>
export const LazySourcesSourcebookDetailsListTitle: LazyComponent<typeof import("../app/components/sources/SourcebookDetailsListTitle.vue").default>
export const LazySourcesSourcebookInTheBox: LazyComponent<typeof import("../app/components/sources/SourcebookInTheBox.vue").default>
export const LazySpellsSpell: LazyComponent<typeof import("../app/components/spells/Spell.vue").default>
export const LazySpellsSpellbookExtra: LazyComponent<typeof import("../app/components/spells/SpellbookExtra.vue").default>
export const LazySpellsSpellbookImage: LazyComponent<typeof import("../app/components/spells/SpellbookImage.vue").default>
export const LazyStripsEditionStrip: LazyComponent<typeof import("../app/components/strips/EditionStrip.vue").default>
export const LazyTabsTabBase: LazyComponent<typeof import("../app/components/tabs/TabBase.vue").default>
export const LazyTeasersSpellTeaser: LazyComponent<typeof import("../app/components/teasers/SpellTeaser.vue").default>
export const LazyTeasersSpellTeaserTile: LazyComponent<typeof import("../app/components/teasers/SpellTeaserTile.vue").default>
export const LazyTeasersTeaserGrid: LazyComponent<typeof import("../app/components/teasers/TeaserGrid.vue").default>
export const LazyTeasersTeaserTile: LazyComponent<typeof import("../app/components/teasers/TeaserTile.vue").default>
export const LazyTeasersTeaserTitle: LazyComponent<typeof import("../app/components/teasers/TeaserTitle.vue").default>
export const LazyTextProseContainer: LazyComponent<typeof import("../app/components/text/ProseContainer.vue").default>
export const LazyUColorModeAvatar: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeAvatar.vue").default>
export const LazyUColorModeButton: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue").default>
export const LazyUColorModeImage: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeImage.vue").default>
export const LazyUColorModeSelect: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSelect.vue").default>
export const LazyUColorModeSwitch: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeSwitch.vue").default>
export const LazyUAccordion: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue").default>
export const LazyUAlert: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Alert.vue").default>
export const LazyUApp: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/App.vue").default>
export const LazyUAuthForm: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/AuthForm.vue").default>
export const LazyUAvatar: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue").default>
export const LazyUAvatarGroup: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.vue").default>
export const LazyUBadge: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue").default>
export const LazyUBanner: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Banner.vue").default>
export const LazyUBlogPost: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/BlogPost.vue").default>
export const LazyUBlogPosts: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/BlogPosts.vue").default>
export const LazyUBreadcrumb: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue").default>
export const LazyUButton: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Button.vue").default>
export const LazyUCalendar: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue").default>
export const LazyUCard: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Card.vue").default>
export const LazyUCarousel: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue").default>
export const LazyUChangelogVersion: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersion.vue").default>
export const LazyUChangelogVersions: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ChangelogVersions.vue").default>
export const LazyUChatMessage: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ChatMessage.vue").default>
export const LazyUChatMessages: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ChatMessages.vue").default>
export const LazyUChatPalette: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ChatPalette.vue").default>
export const LazyUChatPrompt: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ChatPrompt.vue").default>
export const LazyUChatPromptSubmit: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ChatPromptSubmit.vue").default>
export const LazyUCheckbox: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue").default>
export const LazyUCheckboxGroup: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.vue").default>
export const LazyUChip: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Chip.vue").default>
export const LazyUCollapsible: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue").default>
export const LazyUColorPicker: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue").default>
export const LazyUCommandPalette: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue").default>
export const LazyUContainer: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Container.vue").default>
export const LazyUContextMenu: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue").default>
export const LazyUContextMenuContent: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.vue").default>
export const LazyUDashboardGroup: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue").default>
export const LazyUDashboardNavbar: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue").default>
export const LazyUDashboardPanel: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue").default>
export const LazyUDashboardResizeHandle: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DashboardResizeHandle.vue").default>
export const LazyUDashboardSearch: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearch.vue").default>
export const LazyUDashboardSearchButton: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DashboardSearchButton.vue").default>
export const LazyUDashboardSidebar: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue").default>
export const LazyUDashboardSidebarCollapse: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue").default>
export const LazyUDashboardSidebarToggle: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarToggle.vue").default>
export const LazyUDashboardToolbar: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DashboardToolbar.vue").default>
export const LazyUDrawer: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue").default>
export const LazyUDropdownMenu: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue").default>
export const LazyUDropdownMenuContent: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.vue").default>
export const LazyUEditor: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Editor.vue").default>
export const LazyUEditorDragHandle: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/EditorDragHandle.vue").default>
export const LazyUEditorEmojiMenu: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/EditorEmojiMenu.vue").default>
export const LazyUEditorMentionMenu: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/EditorMentionMenu.vue").default>
export const LazyUEditorSuggestionMenu: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/EditorSuggestionMenu.vue").default>
export const LazyUEditorToolbar: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/EditorToolbar.vue").default>
export const LazyUEmpty: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Empty.vue").default>
export const LazyUError: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Error.vue").default>
export const LazyUFieldGroup: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue").default>
export const LazyUFileUpload: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue").default>
export const LazyUFooter: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Footer.vue").default>
export const LazyUFooterColumns: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/FooterColumns.vue").default>
export const LazyUForm: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Form.vue").default>
export const LazyUFormField: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue").default>
export const LazyUHeader: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Header.vue").default>
export const LazyUIcon: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Icon.vue").default>
export const LazyUInput: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Input.vue").default>
export const LazyUInputDate: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputDate.vue").default>
export const LazyUInputMenu: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue").default>
export const LazyUInputNumber: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue").default>
export const LazyUInputTags: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputTags.vue").default>
export const LazyUInputTime: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputTime.vue").default>
export const LazyUKbd: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue").default>
export const LazyULink: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Link.vue").default>
export const LazyULinkBase: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue").default>
export const LazyUMain: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Main.vue").default>
export const LazyUMarquee: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Marquee.vue").default>
export const LazyUModal: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue").default>
export const LazyUNavigationMenu: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue").default>
export const LazyUOverlayProvider: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.vue").default>
export const LazyUPage: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Page.vue").default>
export const LazyUPageAnchors: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageAnchors.vue").default>
export const LazyUPageAside: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageAside.vue").default>
export const LazyUPageBody: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageBody.vue").default>
export const LazyUPageCTA: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageCTA.vue").default>
export const LazyUPageCard: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue").default>
export const LazyUPageColumns: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageColumns.vue").default>
export const LazyUPageFeature: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageFeature.vue").default>
export const LazyUPageGrid: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageGrid.vue").default>
export const LazyUPageHeader: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageHeader.vue").default>
export const LazyUPageHero: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageHero.vue").default>
export const LazyUPageLinks: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageLinks.vue").default>
export const LazyUPageList: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageList.vue").default>
export const LazyUPageLogos: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageLogos.vue").default>
export const LazyUPageSection: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PageSection.vue").default>
export const LazyUPagination: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue").default>
export const LazyUPinInput: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PinInput.vue").default>
export const LazyUPopover: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Popover.vue").default>
export const LazyUPricingPlan: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PricingPlan.vue").default>
export const LazyUPricingPlans: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PricingPlans.vue").default>
export const LazyUPricingTable: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PricingTable.vue").default>
export const LazyUProgress: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue").default>
export const LazyURadioGroup: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue").default>
export const LazyUScrollArea: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ScrollArea.vue").default>
export const LazyUSelect: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Select.vue").default>
export const LazyUSelectMenu: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue").default>
export const LazyUSeparator: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Separator.vue").default>
export const LazyUSkeleton: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue").default>
export const LazyUSlideover: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue").default>
export const LazyUSlider: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Slider.vue").default>
export const LazyUStepper: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue").default>
export const LazyUSwitch: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue").default>
export const LazyUTable: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Table.vue").default>
export const LazyUTabs: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue").default>
export const LazyUTextarea: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue").default>
export const LazyUTimeline: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue").default>
export const LazyUToast: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Toast.vue").default>
export const LazyUToaster: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Toaster.vue").default>
export const LazyUTooltip: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue").default>
export const LazyUTree: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Tree.vue").default>
export const LazyUUser: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/User.vue").default>
export const LazyULocaleSelect: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/locale/LocaleSelect.vue").default>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue").default>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout").default>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only").default>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only").default>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder").default>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link").default>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default>
export const LazyIcon: LazyComponent<typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index").default>
export const LazyColorScheme: LazyComponent<typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue").default>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page").default>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").NoScript>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Link>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Base>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Title>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Meta>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Style>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Head>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Html>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Body>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island").default>

export const componentNames: string[]
